//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laptop_Ecommerce_Shop
{
    using System;
    
    public partial class CustomerCartDatails
    {
        public int CustomerOrderID { get; set; }
        public string ProductName { get; set; }
        public string Brand { get; set; }
        public Nullable<double> Price { get; set; }
        public string Description { get; set; }
        public byte[] image { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> TotalPrice { get; set; }
    }
}
