//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laptop_Ecommerce_Shop
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class ProductFile
    {
        public string FileType { get; set; }
        public byte[] FileContent { get; set; }
        public IEnumerable<HttpPostedFileBase> imgFile { get; set; }
        public IEnumerable<HttpPostedFileBase> videoFile { get; set; }
        public int FileID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> SelectedMainImage { get; set; }
    
        public virtual ProductItem ProductItem { get; set; }
    }
}
